version: '3'

services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - '27017:27017'
        restart: always

    app:
        build: .
        command: npm start
        restart: always
        ports:
            - '4000:4000'
        volumes:
            - .:/usr/app
        environment:
            DATABASE_URL: mongodb://mongo:27017/expressmongo
        depends_on:
            - mongo
